version: '3.7'
services:
  db:
    image: postgres:15
    container_name: config_db
    env_file:
      - .env
    ports:
      - 5432:5432

  redis:
    image: redis:7
    container_name: config_cache

  habits:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: habits_app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command:
      - "docker/app.sh"
    ports:
      - 8000:8000

  celery:
    build: .
    container_name: config_celery
    env_file:
      - .env
    command:
      - "docker/celery.sh"
    depends_on:
      - config

  celery-beat:
    build: .
    container_name: config_celery_beat
    env_file:
      - .env
    command:
       - "docker/celery_beat.sh"
    depends_on:
      - config